### ISSUE TITLE
react-property-selectors: auto select single should not also lock

### ISSUE THREAD

**Issue by bjolind** [promaster-sdk/property#27]
https://github.com/promaster-sdk/property/blob/fcb8d3368bd30aca61e891aaa459af2b96be97ad/packages/react-property-selectors/src/properties-selector/use-properties-selector.tsx#L241

**Comment by jonaskello** [comment]
@Kinatzo This was fixed in #43 so we can close this issue too?

**Comment by Kinatzo** [comment]
> @Kinatzo This was fixed in #43 so we can close this issue too?

Yes!
